{"uuid": "789550ad-82e7-4e17-be0e-5ee96dd72936", "children": ["396bf1d8-6ae1-4e11-aed5-87eda5a6920d"], "befores": [{"name": "appium_driver", "status": "passed", "start": 1725342805174, "stop": 1725342816606}], "afters": [{"name": "appium_driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session/074bc17b-413d-40c2-b101-2dc96034bb5d (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bb2dae0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/shaikmohamedimran/PycharmProjects/E_farm_Mobile_D2FO/Testcases/conftest.py\", line 118, in appium_driver\n    driver.quit()\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 562, in quit\n    self.execute(Command.QUIT)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1725342826268, "stop": 1725342826275}], "start": 1725342805174, "stop": 1725342826275}